apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8080
  name: local
contexts:
- context:
    cluster: local
    namespace: ns
    user: dummy-user
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: dummy-user
  user:
    username: admin
    password: passwd
