name: test
on:
  pull_request:
    branches:
    - main
    - release-*
  push:
    branches:
      - main
      - release-*

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io/llmos-ai' }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || 'docker.io/llmosai' }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: v3.16.2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        check-latest: true
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: make test && make lint
    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        install-only: true
    - name: Build GoReleaser
      run: make build-gpu-stack
    - name: Push Latest(main) Docker Images
      run: |
        . ./scripts/version
        IMAGES=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ${DOCKER_REGISTRY#'docker.io/'}/llmos-gpu-stack:${VERSION})
        for i in ${IMAGES}; do
          docker push $i
        done
        docker manifest create ${{ env.DOCKER_REGISTRY }}/llmos-gpu-stack:${TAG} ${IMAGES}
        docker manifest push ${{ env.DOCKER_REGISTRY }}/llmos-gpu-stack:${TAG}
        docker manifest create ${{ env.DOCKER_REGISTRY }}/llmos-gpu-stack:${VERSION} ${IMAGES}
        docker manifest push ${{ env.DOCKER_REGISTRY }}/llmos-gpu-stack:${VERSION}
    - name: Run build llmos-gpu-stack charts
      run: make package-charts
    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1
#    - name: Run chart-testing (list-changed)
#      id: list-changed
#      run: |
#        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
#        if [[ -n "$changed" ]]; then
#          echo "changed=true" >> "$GITHUB_OUTPUT"
#        fi
    - name: Run chart-testing (lint)
      run: ct lint --target-branch ${{ github.event.repository.default_branch }} --all --chart-dirs dist/charts
    - name: Create kind cluster
      uses: helm/kind-action@v1.10.0
    - name: Run chart-testing (install)
      run: |
        ./scripts/version
        ct install --target-branch ${{ github.event.repository.default_branch }} --charts dist/charts/llmos-gpu-stack-crd
        ct install --target-branch ${{ github.event.repository.default_branch }} --charts dist/charts/llmos-gpu-stack